### ISSUE TITLE
policy = itemnumber? 

### ISSUE THREAD

**Issue by MagnusEnger** [Kreablo/KohaServices#2]
One library has reported that after upgrading to the latest version, the "Loan_Policy" field of the "loan-status" output XML no longer holds the itemtype of the item in question. I think I have tracked it down to this code: 
```
    if (defined $self->params->{policy} && $self->params->{policy} eq 'itemtype' && defined $row->{itemtype_description}) {
        return (1, $row->{itemtype_description});
    }
```
If I change that to:
```
    $self->params->{policy} = 'itemtype';
    if (defined $self->params->{policy} && $self->params->{policy} eq 'itemtype' && defined $row->{itemtype_description}) {
        return (1, $row->{itemtype_description});
    }
```
...it works as expected. So it looks like `$self->params->{policy}` is not getting set when it should. Without that line, `$self->params` only holds one element, `libris_bibid`. 
I have not been able to track down where `$self->params->{policy}` should get set. Any clues?

**Comment by MagnusEnger** [comment]
Still wondering about this. :-) Changing the code to: 
```
    if (defined $row->{itemtype_description}) {
        return (1, $row->{itemtype_description});
    }
```
...makes it work the way our customer wants. I have not been able to figure out where `$self->params->{policy}`should/could get set to 'itemtype'`.

**Comment by AndreasJonsson** [comment]
I'm sorry, I have missed this question!  I have cleaned up my github subscriptions in order to not get a constant flood of notifications.

The idea is that you should set the query parameter itemtype=libris in the link that you configure in the discovery system (i.e., Libris).  So, you shouldn't need to change the source code.

**Comment by MagnusEnger** [comment]
*facepalm* Of course it should be in the URL! Thanks for clarifying that! :-)
